# Derin Ogrenme Egitimi Soru Sayfası

Merhaba değerli katılımcı, kursa başvurun için ilk önce bu repoyu bilgisayarına indirip jupyter notebook ile çalıştırman gerekiyor, bu işlemleri tamamlaman için sana hiçbir yönerge vermiyoruz, çünkü burada amacımız hali hazırda senin bu işlemleri bilip bilmediğini yahut bunları kendi başına öğrenebiliyor musun buna bakmak. Hazırsan senin için de her şeyi hazırladık.


Bu test sayfası bir akış halinde hazırlandı, cevaplayabildiğin soruları cevapladıktan sonra kaydedip bize göndermen gerekiyor.
Hepsini tamamlamak zorunda değilsin, fakat yapamadığın kısımlar üzerinde araştırarak yeni şeylere ne kadar iyi adapte oluyorsun bunu da görmüş olacaksın.

Eğer şuan buradaysan zaten yolun büyük bir kısmını halletmişsin demektir, dosyanı sağ üst taraftaki file menüsünde "download as" sekmesinden ".ipynb" uzantılı olarak indirdikten sonra [Uludag Deep Learning mail adresi](mailto:uludagdeeplearning@gmail.com) gönderebilirsin. Eğer github sayfası açıp ödevini oraya yükledikten sonra ilgili linki bize gönderirsen ekstra puan alacaksın. 

Ödevin son kısmında opsiyonel bir bölüm daha var, gerçekten zor bir bölüm olduğundan emin olabilirsin, son bölümü seçiciliği artırmak için koyuyoruz, şayet çözersen bu senin için ekstra puan demek.

Buradaki her bir satıra hücre deniyor, shift+enter kombinasyonuyla hücreleri çalıştırabilirsin. "Sen zaten bunu biz söylemeden de basitçe çözebilirdin."

In [28]:
isim = input("Isminizi Girin= ")

Isminizi Girin=  Şeyma AKTAŞ


In [29]:
print("Hosgeldin {}, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.".format(isim))

Hosgeldin Şeyma AKTAŞ, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.


## Python

In [5]:
#İleri kullanacağımız fonksiyonlar için bu hücreyi çalıştırın

import numpy as np
import math


### Soru 0:

Python Versiyonunuzu Yazdırın.

In [6]:
#Kodun buraya gelecek

import sys
print("Python versiyonum:",sys.version)

Python versiyonum: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]


### Soru 1:

Telefon numaranızın son hanesindeki rakamdan başlayarak, son iki hanesindeki sayıya kadar devam eden bir liste oluşturun, bu listedeki sayıların ortalamasını ve toplamını yazdırın. (son iki hane sayısı 10'dan küçük olanlar için verilecek değer 70'dir.)

In [27]:
no = int(input("Telefon Numarınızı Girin= "))

Telefon Numarınızı Girin=  5558879895


### Cevap 1:

In [39]:
liste=[] 
toplam=0
a=5
b=95
if b<=10:
    b=70
for i in range(a,b):
    liste.append(i)
    toplam=toplam+i
print("toplam:",toplam)
ortalama=toplam/len(liste)
print("ortalama:",ortalama)
    


toplam: 4455
ortalama: 49.5


### Soru 2:

Alt satırdaki yazi degiskeni olan hücreyi çalıştırın ve for döngüsüyle bu yazının her harfini bir listeye eleman olarak aktarın.

Not: Boşluklar ve noktalama işaretlerini listeye almamalısınız.

In [32]:
yazi = "uludag deeplearning teknik bir topluluktur."


### Cevap 2:

In [38]:
import string
listei=[]
for i in yazi:
    if i !=" " and i not in string.punctuation:
        liste.append(i)
print(liste)
    
    

['u', 'l', 'u', 'd', 'a', 'g', 'd', 'e', 'e', 'p', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 't', 'e', 'k', 'n', 'i', 'k', 'b', 'i', 'r', 't', 'o', 'p', 'l', 'u', 'l', 'u', 'k', 't', 'u', 'r']


### Soru 3:

Sigmoid fonksiyonunu, sigmoid adını verdiğiniz fonksiyonla tanımlayınız.

![sigmoid](sigmoid.jpg)

In [ ]:
# Örnek: 
def fonk_ornek(girdi):
    pass #Burası koduna dahil olmayacak.
    sonuc = islem1*islem2/girdi
    return sonuc

### Cevap 3:

In [15]:
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

## Numpy

### Soru 1:

5x5 boyutunda, sıfırlar, birler matrislerini oluşturun.

### Cevap 1:

In [97]:
a=np.zeros((5,5)) 
b=np.ones((5,5))
print("sıfırlar matrisi:")
print(a)
print("birler matrisi:")
print(b)

sıfırlar matrisi:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
birler matrisi:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Soru 2:

İki farklı 5x5 random sayılardan oluşan iki matris oluşturun. Bu matrisleri matris çarpımı yöntemiyle çarpın

In [12]:
a = np.random.randint(1,100,25)
print("a:")
print(a.reshape(5,5))

print("")

b = np.random.randint(1,100,25)
print("b:")
print(b.reshape(5,5))

c = np.dot(a,b)
print("Matris çarpımı:")
print(c)

a:
[[51 15 73  5 25]
 [34 95 83 77 39]
 [88 87 46 64 98]
 [65 78 64 12 33]
 [62  4 74 91 33]]

b:
[[41 82 85 90 83]
 [80 71 22 79 90]
 [95 31 96 56 56]
 [19 80 20  3 44]
 [92 13 26 94 38]]
Matris çarpımı:
85211


### Soru 3:

100 Uzunluklu bir liste oluşturun, önce tek ve çift sayıları döngülerle tek ve çift adlı iki listeye ayırın, bu iki listeyi 5x10 boyutunda iki matris haline getirin.

### Cevap 3:

In [53]:
a = np.arange(100)
print(a)
print("")

cift = []
tek = []

for i in range(100) :
    if i % 2 == 0 :
        cift.append(i)

    else :
        tek.append(i)
print("Çift: " , np.array(cift) )
x=np.reshape(cift,(5,10))
print(x)
print(" ")
print("Tek :" , np.array(tek))
x=np.reshape(tek,(5,10))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Çift:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
 
Tek : [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]


### Soru 0: (Opsiyonel)

Buradaki matematiksel ifadeleri python ile yazmanızı bekliyoruz. Aşağıda yazılan fonksiyonların her biri size ekstra bazı puanlar kazandıracaktır.

![1.](1.jpg "1")

![3.](3.jpg "3")

![2.](2.jpg "2")